[dependencies]
"@openzeppelin-contracts" = { version = "5.0.2" }
forge-std = { version = "1.9.1" }
solady = { version = "0.0.221" }

[soldeer]
remappings_generated = false
remappings_regenerate = false
remappings_version = false
remappings_prefix = ""
remappings_location = "txt"
recursive_deps = false

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800
bytecode_hash = "none"
evm_version = "shanghai"
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 1000
out = "out"
script = "script"
solc = "0.8.27"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[profile.lite]
optimizer = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
override_spacing = false
quote_style = "double"
single_line_statement_blocks = "multi"
sort_imports = true
tab_width = 4
wrap_comments = true

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

# NOTE: Add any rpc endpoint according to your preference.
[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "${RPC_URL_MAINNET}"
